// This module is the entire SQL capability surface. No model or HTTP input is SQL.
const scope = `SELECT 1 FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1`;
const student = `SELECT TOP (1) p.Etudiant_ID FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1`;
export const queries = Object.freeze({
  children: `SELECT TOP (20) p.EtudiantNiveauAnnee_ID AS enrollmentId,p.Etudiant_Prenom AS firstName,p.Etudiant_DateNaissance AS dateOfBirth,p.Classe_Libelle AS className,p.Annee_Libelle AS schoolYear FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.Annee_Encours=1 ORDER BY p.EtudiantNiveauAnnee_ID`,
  learning: `SELECT TOP (60) l.ResultatApprentissage_Date AS observedAt,l.ComposanteCours_Lecon AS skill,l.Matiere_DefinitionComplet AS subject,l.NiveauApprentissage_Libelle AS status FROM dbo.VConsultation_Resultat_Apprentissage l WHERE l.ResultatApprentissage_EtudiantNiveauAnnee_Id=@enrollmentId AND EXISTS (${scope}) ORDER BY l.ResultatApprentissage_Date DESC,l.ResultatApprentissage_Id DESC`,
  attendance: `SELECT TOP (40) a.Absence_Date_Du AS dateFrom,a.Absence_Date_Au AS dateTo,a.Matiere_Definition AS subject,ab.Absence_Libelle AS label,ab.Absence_Justifie AS justified,ab.Absence_Justification AS justification FROM dbo.VAbsenceMatiere a INNER JOIN dbo.Absence ab ON ab.EtudiantNiveauAnnee_ID=a.EtudiantNiveauAnnee_ID AND ab.Absence_Date_Du=a.Absence_Date_Du AND ab.Matiere_ID=a.Matiere_ID WHERE a.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope}) ORDER BY a.Absence_Date_Du DESC`,
  messages: `SELECT TOP (30) m.Message_Titre AS title,m.Message_Text AS text,m.Message_DateCreation AS observedAt FROM dbo.VConsultation_MessageDirection m WHERE m.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope}) ORDER BY m.Message_DateCreation DESC,m.Message_ID DESC`,
  homework: `SELECT TOP (30) d.Devoirs_Description AS description,d.Devoirs_Date AS dueDate FROM dbo.Devoirs d WHERE d.Devoirs_Date>=DATEADD(day,-60,GETDATE()) AND d.Devoirs_Date<=DATEADD(day,45,GETDATE()) AND EXISTS (SELECT 1 FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1 AND p.Classe_ID=d.Classe_ID) ORDER BY d.Devoirs_Date DESC,d.Devoirs_ID DESC`,
  journey: `SELECT TOP (12) a.Annee_Libelle AS schoolYear,c.Classe_Libelle AS className,n.Niveau_Libelle AS levelName,a.Annee_Encours AS isCurrent FROM dbo.Etudiant_Niveau_Annee ena INNER JOIN dbo.Annee a ON a.Annee_ID=ena.Annee_ID INNER JOIN dbo.Niveau n ON n.Niveau_ID=ena.Niveau_ID OUTER APPLY (SELECT TOP (1) cl.Classe_Libelle FROM dbo.Etudiant_Classe ec INNER JOIN dbo.Classe cl ON cl.Classe_ID=ec.Classe_ID WHERE ec.EtudiantNiveauAnnee_ID=ena.EtudiantNiveauAnnee_ID ORDER BY ec.EtudiantClasse_ID DESC) c WHERE ena.Etudiant_ID=(${student}) AND EXISTS (${scope}) ORDER BY a.Annee_ID DESC`,
  yearResults: `SELECT TOP (12) s.schoolYear,COUNT(CASE WHEN s.score20 IS NOT NULL THEN 1 END) AS noteCount,ROUND(AVG(s.score20),2) AS average20,ROUND(MIN(s.score20),2) AS minimum20,ROUND(MAX(s.score20),2) AS maximum20,SUM(CASE WHEN s.score20 IS NULL THEN 1 ELSE 0 END) AS discardedCount FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE EXISTS (${scope}) GROUP BY s.schoolYear ORDER BY s.schoolYear`,
  subjectResults: `SELECT TOP (60) s.schoolYear,s.subject,COUNT(s.score20) AS noteCount,ROUND(AVG(s.score20),2) AS average20 FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,x.Matiere_DefinitionComplet AS subject,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE s.score20 IS NOT NULL AND EXISTS (${scope}) GROUP BY s.schoolYear,s.subject ORDER BY s.schoolYear,s.subject`,
  termResults: `SELECT TOP (24) s.schoolYear,s.term,COUNT(s.score20) AS noteCount,ROUND(AVG(s.score20),2) AS average20 FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,x.Periode_Libelle AS term,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE s.score20 IS NOT NULL AND EXISTS (${scope}) GROUP BY s.schoolYear,s.term ORDER BY s.schoolYear,s.term`,
});
export const privilegeCheck = `SELECT 'WRITE_CAPABILITY' AS writableObject WHERE EXISTS (SELECT 1 FROM sys.objects o WHERE o.type IN ('U','V') AND o.is_ms_shipped=0 AND (HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','INSERT')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','UPDATE')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','DELETE')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','ALTER')=1)) OR EXISTS (SELECT 1 FROM sys.fn_my_permissions(NULL,'DATABASE') WHERE permission_name IN ('CONTROL','ALTER','CREATE TABLE','CREATE PROCEDURE','ALTER ANY USER','ALTER ANY ROLE'))`;
export function queryByName(name) {
  if (!Object.hasOwn(queries, name)) throw new Error("QUERY_NOT_ALLOWED");
  return queries[name];
}
export function requireIdentity(subject, mapping) {
  if (
    typeof subject !== "string" ||
    subject.startsWith("demo-") ||
    !Object.hasOwn(mapping, subject) ||
    !Number.isSafeInteger(mapping[subject]) ||
    mapping[subject] <= 0
  )
    throw new Error("VERIFIED_IDENTITY_REQUIRED");
  return mapping[subject];
}
