// This module is the entire SQL capability surface. No model or HTTP input is SQL.
const scope = `SELECT 1 FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1`;
const student = `SELECT TOP (1) p.Etudiant_ID FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1`;
const currentClass = `SELECT TOP (1) p.Classe_ID FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.EtudiantNiveauAnnee_ID=@enrollmentId AND p.Annee_Encours=1`;
const currentYear = `SELECT TOP (1) ena.Annee_ID FROM dbo.Etudiant_Niveau_Annee ena WHERE ena.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope})`;
export const queries = Object.freeze({
  children: `SELECT TOP (20) p.EtudiantNiveauAnnee_ID AS enrollmentId,p.Etudiant_Prenom AS firstName,p.Etudiant_DateNaissance AS dateOfBirth,p.Classe_Libelle AS className,p.Annee_Libelle AS schoolYear FROM dbo.VCondultation_Parent_Etudiant p WHERE p.Parent_ID=@parentId AND p.Annee_Encours=1 ORDER BY p.EtudiantNiveauAnnee_ID`,
  learning: `SELECT TOP (60) l.ResultatApprentissage_Date AS observedAt,l.ComposanteCours_Lecon AS skill,l.Matiere_DefinitionComplet AS subject,l.NiveauApprentissage_Libelle AS status FROM dbo.VConsultation_Resultat_Apprentissage l WHERE l.ResultatApprentissage_EtudiantNiveauAnnee_Id=@enrollmentId AND EXISTS (${scope}) ORDER BY l.ResultatApprentissage_Date DESC,l.ResultatApprentissage_Id DESC`,
  attendance: `SELECT TOP (40) a.Absence_Date_Du AS dateFrom,a.Absence_Date_Au AS dateTo,a.Matiere_DefinitionComplet AS subject,a.Absence_Libelle AS label,a.Absence_Justifie AS justified FROM dbo.V_Consultation_Absence a WHERE a.Parent_ID=@parentId AND a.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope}) ORDER BY a.Absence_Date_Du DESC,a.Absence_ID DESC`,
  assiduity: `SELECT TOP (40) a.Assiduite_Date AS observedAt,a.Matiere_DefinitionComplet AS subject,a.AssiduiteMotif_Libelle AS label,a.Assiduite_Commentaire AS comment FROM dbo.V_ConsultationAssiduite a WHERE a.Parent_ID=@parentId AND a.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope}) ORDER BY a.Assiduite_Date DESC,a.Assiduite_ID DESC`,
  messages: `SELECT TOP (30) m.Message_Titre AS title,m.Message_Text AS text,m.Message_DateCreation AS observedAt FROM dbo.VConsultation_MessageDirection m WHERE m.EtudiantNiveauAnnee_ID=@enrollmentId AND EXISTS (${scope}) ORDER BY m.Message_DateCreation DESC,m.Message_ID DESC`,
  homework: `SELECT TOP (30) d.Document_Description AS description,d.Document_Date AS publishedAt,d.Document_DateRealisation AS dueDate,d.Matiere_DefinitionComplet AS subject,d.DocumentPartageType_Libelle AS documentType FROM dbo.VDocementPartageType d WHERE d.Classe_ID=(${currentClass}) AND d.Annee_ID=(${currentYear}) AND d.Document_Flag=1 AND d.DocumentPartageType_Libelle=N'Devoir à la maison' AND COALESCE(d.Document_DateRealisation,d.Document_Date)>=DATEADD(day,-60,CONVERT(date,GETDATE())) AND COALESCE(d.Document_DateRealisation,d.Document_Date)<=DATEADD(day,45,CONVERT(date,GETDATE())) AND EXISTS (${scope}) ORDER BY COALESCE(d.Document_DateRealisation,d.Document_Date) ASC,d.Document_ID DESC`,
  exams: `SELECT TOP (30) e.Examen_Date AS examDate,e.Examen_Libelle AS exam,e.Matiere_DefinitionComplet AS subject,e.TypeExamen_Libelle AS examType,e.Periode_Libelle AS term,e.Annee_Libelle AS schoolYear FROM dbo.V_Consultation_Examen e WHERE e.Classe_ID=(${currentClass}) AND e.Annee_ID=(${currentYear}) AND e.Examen_Date BETWEEN DATEADD(day,-30,CONVERT(date,GETDATE())) AND DATEADD(day,90,CONVERT(date,GETDATE())) AND EXISTS (${scope}) ORDER BY e.Examen_Date ASC,e.Examen_ID DESC`,
  latestMarks: `WITH completedYear AS (SELECT TOP (1) x.Annee_ID,x.Annee_Libelle FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND ISNULL(x.Annee_Encours,0)=0 ORDER BY x.Annee_ID DESC),ranked AS (SELECT x.Annee_Libelle AS schoolYear,x.Matiere_DefinitionComplet AS subject,x.Examen_Libelle AS exam,x.Examen_Date AS examDate,x.ExamenNote_Valeur AS rawScore,x.Examen_Division AS scale,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN ROUND(x.ExamenNote_Valeur*20.0/x.Examen_Division,2) END AS score20,ROW_NUMBER() OVER (PARTITION BY x.Matiere_ID ORDER BY x.Examen_Date DESC,x.ExamenNote_ID DESC) AS rowNumber FROM dbo.V_Consultation_ExamenNote x INNER JOIN completedYear y ON y.Annee_ID=x.Annee_ID WHERE x.Etudiant_ID=(${student})) SELECT TOP (30) schoolYear,subject,exam,examDate,rawScore,scale,score20 FROM ranked WHERE rowNumber=1 AND score20 IS NOT NULL AND EXISTS (${scope}) ORDER BY subject`,
  markDetails: `SELECT TOP (250) x.Annee_Libelle AS schoolYear,x.Periode_Libelle AS term,x.Matiere_DefinitionComplet AS subject,x.Examen_Libelle AS exam,x.Examen_Date AS examDate,x.ExamenNote_Valeur AS rawScore,x.Examen_Division AS scale,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN ROUND(x.ExamenNote_Valeur*20.0/x.Examen_Division,2) END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division AND EXISTS (${scope}) ORDER BY x.Annee_ID,x.Matiere_DefinitionComplet,x.Examen_Date,x.ExamenNote_ID`,
  competencies: `SELECT TOP (150) s.EvaluationCompetence_MatiereId,s.Matiere_DefinitionComplet AS subject,s.CompetanceCible_Description AS competency,s.CompetanceCible_Recurant AS recurring,s.CompetanceCible_Code AS code,s.Examen_Date AS examDate,s.EvaluationCompetence_Score AS score FROM dbo.V_CONSULTATION_ETUDIANT_EVALUATION_SCORE s WHERE s.EvaluationCompetence_EtudiantId=(${student}) AND EXISTS (${scope}) ORDER BY s.Examen_Date DESC,s.EvaluationCompetence_Id DESC`,
  teachers: `SELECT DISTINCT TOP (20) pc.Classe_Libelle AS className,pm.Matiere_DefinitionComplet AS subject,pr.Professeur_Nom AS lastName,pr.Professeur_Prenom AS firstName FROM dbo.V_CONSULTATION_PROF_CLASSE pc INNER JOIN dbo.V_Consultation_Professeur_Avec_Classe pr ON pr.Professeur_ID=pc.Professeur_ID AND pr.Niveau_ID=pc.Niveau_ID INNER JOIN dbo.VConsultation_Professeur_NiveauMatiere pm ON pm.Professeur_ID=pc.Professeur_ID WHERE pc.Classe_ID=(${currentClass}) AND EXISTS (${scope}) ORDER BY subject,lastName,firstName`,
  activities: `SELECT TOP (20) a.Annee_Libelle AS schoolYear,a.ActiviteType_Libelle AS activityType,a.Activite_Description AS activity,a.Activite_Date AS activityDate,a.Classe_Libelle AS className FROM dbo.VACTIVITE_INSCRIPTION a WHERE a.ActiviteInscription_EtudiantId=(${student}) AND EXISTS (${scope}) ORDER BY a.Activite_Date DESC,a.ActiviteInscription_Id DESC`,
  journey: `SELECT TOP (12) a.Annee_Libelle AS schoolYear,c.Classe_Libelle AS className,n.Niveau_Libelle AS levelName,a.Annee_Encours AS isCurrent FROM dbo.Etudiant_Niveau_Annee ena INNER JOIN dbo.Annee a ON a.Annee_ID=ena.Annee_ID INNER JOIN dbo.Niveau n ON n.Niveau_ID=ena.Niveau_ID OUTER APPLY (SELECT TOP (1) cl.Classe_Libelle FROM dbo.Etudiant_Classe ec INNER JOIN dbo.Classe cl ON cl.Classe_ID=ec.Classe_ID WHERE ec.EtudiantNiveauAnnee_ID=ena.EtudiantNiveauAnnee_ID ORDER BY ec.EtudiantClasse_ID DESC) c WHERE ena.Etudiant_ID=(${student}) AND EXISTS (${scope}) ORDER BY a.Annee_ID DESC`,
  yearResults: `SELECT TOP (12) s.schoolYear,COUNT(CASE WHEN s.score20 IS NOT NULL THEN 1 END) AS noteCount,ROUND(AVG(s.score20),2) AS average20,ROUND(MIN(s.score20),2) AS minimum20,ROUND(MAX(s.score20),2) AS maximum20,SUM(CASE WHEN s.score20 IS NULL THEN 1 ELSE 0 END) AS discardedCount FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE EXISTS (${scope}) GROUP BY s.schoolYear ORDER BY s.schoolYear`,
  subjectResults: `SELECT TOP (60) s.schoolYear,s.subject,COUNT(s.score20) AS noteCount,ROUND(AVG(s.score20),2) AS average20 FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,x.Matiere_DefinitionComplet AS subject,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE s.score20 IS NOT NULL AND EXISTS (${scope}) GROUP BY s.schoolYear,s.subject ORDER BY s.schoolYear,s.subject`,
  termResults: `SELECT TOP (24) s.schoolYear,s.term,COUNT(s.score20) AS noteCount,ROUND(AVG(s.score20),2) AS average20 FROM (SELECT DISTINCT x.ExamenNote_ID,x.Annee_Libelle AS schoolYear,x.Periode_Libelle AS term,CASE WHEN x.Examen_Division>0 AND x.ExamenNote_Valeur>=0 AND x.ExamenNote_Valeur<=x.Examen_Division THEN x.ExamenNote_Valeur*20.0/x.Examen_Division END AS score20 FROM dbo.V_Consultation_ExamenNote x WHERE x.Etudiant_ID=(${student}) AND x.Annee_Libelle IN (N'2023/2024',N'2024/2025')) s WHERE s.score20 IS NOT NULL AND EXISTS (${scope}) GROUP BY s.schoolYear,s.term ORDER BY s.schoolYear,s.term`,
});
export const privilegeCheck = `SELECT 'WRITE_CAPABILITY' AS writableObject WHERE EXISTS (SELECT 1 FROM sys.objects o WHERE o.type IN ('U','V') AND o.is_ms_shipped=0 AND (HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','INSERT')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','UPDATE')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','DELETE')=1 OR HAS_PERMS_BY_NAME(QUOTENAME(SCHEMA_NAME(o.schema_id))+'.'+QUOTENAME(o.name),'OBJECT','ALTER')=1)) OR EXISTS (SELECT 1 FROM sys.fn_my_permissions(NULL,'DATABASE') WHERE permission_name IN ('CONTROL','ALTER','CREATE TABLE','CREATE PROCEDURE','ALTER ANY USER','ALTER ANY ROLE'))`;
export function queryByName(name) {
  if (!Object.hasOwn(queries, name)) throw new Error("QUERY_NOT_ALLOWED");
  return queries[name];
}
export function requireIdentity(subject, mapping) {
  if (
    typeof subject !== "string" ||
    subject.startsWith("demo-") ||
    !Object.hasOwn(mapping, subject) ||
    !Number.isSafeInteger(mapping[subject]) ||
    mapping[subject] <= 0
  )
    throw new Error("VERIFIED_IDENTITY_REQUIRED");
  return mapping[subject];
}
